### ISSUE TITLE
[Enhancement] Conversion of Script into QBCORE

### ISSUE THREAD

**Issue by Tamer173** [Azerothwav/Az_parking#1]
If this script can be Converted to QBCore , then it will become very Demanding and Popular !

Az team Please convert this to QBCore It will be very Helpful

**Comment by Azerothwav** [comment]
The az_parking is a very old version (the one of my github), a new version should arrive in the near future that brings it up to date,
who would be for ESX / QBCore and custom framework ^^
Thank you for taking such an interest in my scripts, I do my best to bring you the best experience possible 👍

**Comment by Tamer173** [comment]
> The az_parking is a very old version (the one of my github), a new version should arrive in the near future that brings it up to date, who would be for ESX / QBCore and custom framework ^^ Thank you for taking such an interest in my scripts, I do my best to bring you the best experience possible 👍

I support the script because its the best one out there with most responsive and bug free, keep up the good work
